Adapt prefix test for CI process
Signed-off-by: Alex Nelson <alexander.nelson@nist.gov>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -24,7 +24,7 @@ jobs:
 
       - name: Install Dependencies
         run: |
-          pip -q install poetry pre-commit
+          pip -q install poetry pre-commit rdflib
           poetry install
 
       - name: Pre-commit Checks
@@ -43,6 +43,11 @@ jobs:
           case-path: ./
           case-version: "case-1.3.0"
           extension-filter: "jsonld"
+
+      - name: Convert example
+        run: |
+          rdfpipe --output-format turtle case.jsonld > case.ttl
+          test 0 -eq $(grep 'file:' case.ttl | wc -l) || (echo "ERROR:ci.yml:Some graph IRIs do not supply a resolving prefix.  Look for the string 'file:///' in the file case.ttl (created by running 'make check') to see these instances." >&2 ; exit 1)
 
       # Always build the package as a sanity check to ensure no issues with the build system
       # exist as part of the CI process
